import os
import torch
import numpy as np
from tqdm import tqdm
import pickle

def normalize_GTSF(cfg, trainset, testset):
    """
    Normalize data based on trainset stats and apply to trainset + testset.
    Saves processed data under normalized_path.
    """
    processed_path = cfg.processed_dir
    normalized_path = cfg.normalized_dir
    min_max_file = cfg.data_stats_filename
    recalculate_min_max = cfg.recalculate_data_stats
    log_normalize = cfg.log_normalize

    # Step 1: compute or load stats (from trainset only)
    if recalculate_min_max or not os.path.exists(min_max_file):
        print("Computing min/max from trainset...")
        min_values, max_values = compute_min_max_from_dataset(trainset)
        save_min_max(min_max_file, min_values, max_values)
    else:
        print("Loading min/max...")
        min_values, max_values = load_min_max(min_max_file)

    # Step 2: normalize static file + all data (train + test)
    print("Normalizing and saving data...")
    os.makedirs(normalized_path, exist_ok=True)

    static_file_in = os.path.join(processed_path, "data_static.pt")
    static_file_out = os.path.join(normalized_path, "data_static.pt")
    if os.path.exists(static_file_in):
        data_static = torch.load(static_file_in)
        # do not normalize all properties, only x/node_labels/edge_attr as needed
        data_static_normalized = normalize_data(data_static, min_values, max_values, log_normalize, data_static.x.shape[1])
        os.makedirs(os.path.dirname(static_file_out), exist_ok=True)
        torch.save(data_static_normalized, static_file_out)

    all_data = list(trainset) + list(testset)
    for data_entry in tqdm(all_data, desc="Normalizing"):
        # data_entry may be a list of Data objects (time series) or a single Data object.
        sequence = data_entry if isinstance(data_entry, list) else [data_entry]

        # Normalize each timestep in the sequence
        normalized_sequence = [normalize_data(d, min_values, max_values, log_normalize, d.x.shape[1]) for d in sequence]

        for data_obj, normalized_obj in zip(sequence, normalized_sequence):
            if hasattr(data_obj, 'path'):
                save_path = data_obj.path.replace(processed_path, normalized_path)
                os.makedirs(os.path.dirname(save_path), exist_ok=True)
                torch.save(normalized_obj, save_path)
            else:
                # Fallback: save in normalized_path with autogenerated names
                if not hasattr(data_obj, 'scenario') or not hasattr(data_obj, 'step'):
                    raise ValueError("Data object must have 'scenario' and 'step' or 'path' to save")
                save_path = os.path.join(normalized_path, f"scenario{data_obj.scenario}", f"data_{data_obj.scenario}_{data_obj.step}.pt")
                os.makedirs(os.path.dirname(save_path), exist_ok=True)
                torch.save(normalized_obj, save_path)

    print("Normalization complete.")

def compute_min_max_from_dataset(dataset):
    """Compute min/max stats from a dataset (e.g., trainset)."""
    min_values = None
    max_values = None
    for data_entry in tqdm(dataset, desc="Collecting stats"):
        sequence = data_entry if isinstance(data_entry, list) else [data_entry]

        for data in sequence:
            x_np = data.x.numpy()
            node_labels_np = data.node_labels.numpy()
            edge_attr_np = data.edge_attr.numpy() if data.edge_attr.size(0) > 0 else None

            if min_values is None:
                min_values = {
                    "x": np.min(x_np, axis=0),
                    "node_labels": np.min(node_labels_np, axis=0),
                    "edge_attr": np.min(edge_attr_np, axis=0) if edge_attr_np is not None else None,
                    "y": data.y,
                    "y_cummulative": data.y_cummulative
                }
                max_values = {
                    "x": np.max(x_np, axis=0),
                    "node_labels": np.max(node_labels_np, axis=0),
                    "edge_attr": np.max(edge_attr_np, axis=0) if edge_attr_np is not None else None,
                    "y": data.y,
                    "y_cummulative": data.y_cummulative
                }
            else:
                min_values["x"] = np.minimum(min_values["x"], np.min(x_np, axis=0))
                max_values["x"] = np.maximum(max_values["x"], np.max(x_np, axis=0))

                min_values["node_labels"] = np.minimum(min_values["node_labels"], np.min(node_labels_np, axis=0))
                max_values["node_labels"] = np.maximum(max_values["node_labels"], np.max(node_labels_np, axis=0))

                if edge_attr_np is not None:
                    min_values["edge_attr"] = np.minimum(min_values["edge_attr"], np.min(edge_attr_np, axis=0))
                    max_values["edge_attr"] = np.maximum(max_values["edge_attr"], np.max(edge_attr_np, axis=0))

                min_values["y"] = min(min_values["y"], data.y)
                max_values["y"] = max(max_values["y"], data.y)

                min_values["y_cummulative"] = min(min_values["y_cummulative"], data.y_cummulative)
                max_values["y_cummulative"] = max(max_values["y_cummulative"], data.y_cummulative)

    return min_values, max_values

def normalize_data(data, min_values, max_values, log_normalize, num_features):
    """Normalisiert ein einzelnes Data-Objekt (wie in deinem Original)."""
    # Kopie erstellen
    normalized_data = data.clone()
    
    # Beispiel für x (anpassen für alle Felder)
    for i in range(num_features):
        if log_normalize:
            # Log-Normalisierung (deine Logik)
            pass  # Implementiere wie in Original
        else:
            # Min-Max Normalisierung
            normalized_data.x[:, i] = (data.x[:, i] - min_values["x"][i]) / (max_values["x"][i] - min_values["x"][i])
    
    # Ähnlich für node_labels, edge_attr etc.
    # (Vollständig aus deinem Original übernehmen)
    
    return normalized_data

def save_min_max(file_path, min_values, max_values):
    """Speichert Min/Max."""
    with open(file_path, 'wb') as f:
        pickle.dump({'min_values': min_values, 'max_values': max_values}, f)

def load_min_max(file_path):
    """Lädt Min/Max."""
    with open(file_path, 'rb') as f:
        data = pickle.load(f)
    return data['min_values'], data['max_values']